### ISSUE TITLE
TODO cleanup compilation

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#3490]
Faucet has a lot of TODOs lying around. I will be moving those TODOs, along with their age (as of writing this) into this issue and we can discuss whether they are still valid etc..

- faucet/fctl.py
    - [ ] [3yr] This script and its usage is experimental and its output is expected to change significantly.
    https://github.com/faucetsdn/faucet/blob/19678f3a2df295e26ceaf288bbb63e230d92815d/faucet/fctl.py#L5
    - [ ] [3yr] Add control functionality.
    https://github.com/faucetsdn/faucet/blob/19678f3a2df295e26ceaf288bbb63e230d92815d/faucet/fctl.py#L7
    - [ ] [3yr] Byte/packet counters could be per second (given multiple samples)
    https://github.com/faucetsdn/faucet/blob/19678f3a2df295e26ceaf288bbb63e230d92815d/faucet/fctl.py#L37

- faucet/faucet_event.py
    - [ ] [2yr] Events are currently schema-less. This is to facilitate rapid prototyping, and will change.
    https://github.com/faucetsdn/faucet/blob/f15cb17b38a74ca4f2325254bce8dd503e43af57/faucet/faucet_event.py#L3
    - [ ] [2yr] Not all cases where a notified client fails or could block, have been tested. Only one client is supported (multiple clients should be implemented with a client that copies/pushes to a message bus)
    https://github.com/faucetsdn/faucet/blob/f15cb17b38a74ca4f2325254bce8dd503e43af57/faucet/faucet_event.py#L4

- travis/runtests.sh
    - [ ] [10mo] run a standalone DP and also a stacked DP test to test hardware linkages.
    https://github.com/faucetsdn/faucet/blob/d75c3d00f1bfbfb0f66ea607dff054a6e932e91b/travis/runtests.sh#L95
   - [ ] [11mo] automatically run gdb?
   https://github.com/faucetsdn/faucet/blob/d75c3d00f1bfbfb0f66ea607dff054a6e932e91b/travis/runtests.sh#L104

- tests/unit/faucet/valve_test_lib.py
    - [ ] [2yr] Verify events
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L513
    - [ ] [2yr] Verify learn caching
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L771
    - [ ] [2yr] Verify host learning banned
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L778
    - [ ] [2yr] Verify state expired
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L809
    - [ ] [2yr] VLAN packet submitted to packet in always has VID
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L880
    - [ ] [2yr] Verify TFM content
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1021
    - [ ] [2yr] Check ARP reply is valid
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1081
    - [ ] [2yr] Check ARP reply is valid
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1092
    - [ ] [2yr] Check reply NA is valid
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1111
    - [ ] [2yr] Check NA response flows are valid
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1124
    - [ ] [2yr] Check RA is valid
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1138
    - [ ] [2yr] Check ARP reply is valid
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1178
    - [ ] [2yr] Check add flows
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1185
    - [ ] [2yr] Check del flows
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1189
    - [ ] [2yr] Verify learning rule contents
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1202
    - [ ] [2yr] Verify learning rule contents
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1222
    - [ ] [2yr] Check proactive neighbor resolution
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1237
    - [ ] [2yr] Check proactive neighbor resolution
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1249
    - [ ] [2yr] Verify LLDP packet content
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1661
    - [ ] [6 mo] Test actual config contents
    https://github.com/faucetsdn/faucet/blob/a930f7cf59458b9c67101ae5806a814ad22590d1/tests/unit/faucet/valve_test_lib.py#L1744

- faucet/valve_table.py
    - [ ] [2yr] Verify actions
    https://github.com/faucetsdn/faucet/blob/863b5a9f1ff5a12770a64a4794dedbe98965c568/faucet/valve_table.py#L94
    - [ ] [11mo] ACL builder should not use ALL table
    https://github.com/faucetsdn/faucet/blob/863b5a9f1ff5a12770a64a4794dedbe98965c568/faucet/valve_table.py#L117

- docker/runtests.sh
    - [ ] [2yr] Need to force UTF-8 as POSIX causes python3/pytype errors
    https://github.com/faucetsdn/faucet/blob/d75c3d00f1bfbfb0f66ea607dff054a6e932e91b/docker/runtests.sh#L127
    - [ ] [10mo] Randomize OF port range (offset from 1 for basic test)
    https://github.com/faucetsdn/faucet/blob/d75c3d00f1bfbfb0f66ea607dff054a6e932e91b/docker/runtests.sh#L189

- faucet/faucet_bgp.py
    - [ ] [2yr] Delete RIB routes for down peer
    https://github.com/faucetsdn/faucet/blob/340b519860693526b0f18b65e7234864754f7e8d/faucet/faucet_bgp.py#L94
    - [ ] [12mo] Port status changes should cause us to withdraw a route
    https://github.com/faucetsdn/faucet/blob/340b519860693526b0f18b65e7234864754f7e8d/faucet/faucet_bgp.py#L218
    - [ ] [2yr] Shutdown and remove deconfigured BGP speakers
    https://github.com/faucetsdn/faucet/blob/340b519860693526b0f18b65e7234864754f7e8d/faucet/faucet_bgp.py#L223

- faucet/prom_client.py
    - [x] [2yr] Investigate faster alternative (https://bugs.launchpad.net/pbr/+bug/1688405)
    https://github.com/faucetsdn/faucet/blob/c4f131de83c96a95d1d715c2a5e510ebfb3abef6/faucet/prom_client.py#L56
    Marked `Fix Released` on 2018-04-25

- faucet/gauge_pollers.py
    - [ ] [3yr] It may be worthwhile verifying this is the correct stats response before doing this
    https://github.com/faucetsdn/faucet/blob/52c1e227778988d7e806d677b9498f31ff32d22f/faucet/gauge_pollers.py#L99
    - [ ] [3yr] This should use a deterministic method instead of random
    https://github.com/faucetsdn/faucet/blob/52c1e227778988d7e806d677b9498f31ff32d22f/faucet/gauge_pollers.py#L186

To be continued...

**Comment by mab68** [comment]
- faucet/faucet_pipeline.py
    - [ ] [2yr] Implement an eth_type table before VLAN. This would enable interception of control protocols and simplify matches in vlan/eth_src, enabling use of exact_match
    https://github.com/faucetsdn/faucet/blob/70d83686f11da88aa1c83080c2105d3e44d6a7f9/faucet/faucet_pipeline.py#L180


- faucet/gauge_prom.py
    - [ ] [] Labels based on matches will be dynamic
    https://github.com/faucetsdn/faucet/blob/52c1e227778988d7e806d677b9498f31ff32d22f/faucet/gauge_prom.py#L171


- clib/clib_mininet_test_main.py
    - [ ] [6mo] Tested with OVS userspace only
    https://github.com/faucetsdn/faucet/blob/155446fb9b15042560d846e6292589e0106d5d62/clib/clib_mininet_test_main.py#L49
    - [ ] [2yr] Test other stacking combinations
    https://github.com/faucetsdn/faucet/blob/155446fb9b15042560d846e6292589e0106d5d62/clib/clib_mininet_test_main.py#L359
    - [ ] [2yr] Tests that are serialized generally depend on hardcoded ports. Make then use dynamic ports.
    https://github.com/faucetsdn/faucet/blob/155446fb9b15042560d846e6292589e0106d5d62/clib/clib_mininet_test_main.py#L486


- faucet/acl.py
    - [x] [14mo] Would be possible to save the names instead of the DP and port objects
    https://github.com/faucetsdn/faucet/blob/64ebec166eb75cb3900a311dfe87bbb1f55398f4/faucet/acl.py#L116
    Fixed by #3476. ACL tunnel information dictionary uses DP names and port numbers.
    - [x] [14mo] Choose what combinations of matches & actions to disallow with a tunnel
    https://github.com/faucetsdn/faucet/blob/64ebec166eb75cb3900a311dfe87bbb1f55398f4/faucet/acl.py#L308
    Fixed by #3476. With the inclusion of ordered ACL actions, tunnel rules should work with all other action types.


- faucet/valves_manager.py
    - [ ] [2yr] Better to use an inotify method that doesn't conflict with eventlets.
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/faucet/valves_manager.py#L52
    - [ ] [7mo] Timeout should be configurable
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/faucet/valves_manager.py#L113


- faucet/dp.py
    - [ ] [1mo] Not supported by OVS in 2.7.0
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L100
    - [ ] [1mo] Not supported by OVS in 2.7.0
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L101
    - [ ] [2yr] Dynamically configure output attribute
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L475
    - [ ] [2yr] Confusingly, mirror at config time means what ports to mirror from. But internally, we use as a list of ports to mirror to.
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L1077
    - [ ] [2yr] Move this config validation to ACL object
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L1183
    - [ ] [2yr] Optimize case were only VLAN ACL changed
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L1449
    - [ ] [8dy] Limit scope to only routers that have affected VLANs
    https://github.com/faucetsdn/faucet/blob/b73ec09d3005c7e64d6f1c14201a999ae55b2fe4/faucet/dp.py#L1528


- tests/unit/faucet/test_check_config.py
    - [ ] [2yr] Check acls_in work now acl_in is deprecated, remove in future
    https://github.com/faucetsdn/faucet/blob/bbe3246a2a593876c5319efb0ed19222fc47c598/tests/unit/faucet/test_check_config.py#L56

**Comment by mab68** [comment]
- clib/mininet_test_base.py
    - [ ] [7mo] Occasionally fails with socket error
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L424
    - [ ] [2yr] Seemingly can't have more than one namespace
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L650
    - [ ] [1mo] Should this have meter_confs as well or can we just match meter_ids
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L989
    - [ ] [2yr] Ryu ofctl serializes to old matches
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L1001
    - [ ] [2yr] Verify port/host association, not just that host moved.
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L1579
    - [ ] [2yr] Test environment is pretty hard on test host, with this many macvlans
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L1729
    - [ ] [3yr] Account for drops
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L2126
    - [ ] [2yr] VIP might not be in neigbor teable if still tentative/ND used non VIP source address. Make test host source address consistent.
    https://github.com/faucetsdn/faucet/blob/a074fc10dedfae43ef9468cddb41902a203fbe27/clib/mininet_test_base.py#L2331

- clib/mininet_test_topo.py
    - [ ] [11mo] This should be configurable (e.g. for randomization)
    https://github.com/faucetsdn/faucet/blob/d75c3d00f1bfbfb0f66ea607dff054a6e932e91b/clib/mininet_test_topo.py#L26
    - [ ] [7mo] This can be simplified when we update mininet in the test image
    https://github.com/faucetsdn/faucet/blob/d75c3d00f1bfbfb0f66ea607dff054a6e932e91b/clib/mininet_test_topo.py#L45


- tests/unit/faucet/fakeoftable.py
    - [ ] [2yr] Handle OFPMeterMod
    https://github.com/faucetsdn/faucet/blob/e125b87385f3b1537ec92ff0c71ee4c566a1250b/tests/unit/faucet/fakeoftable.py#L212
    - [ ] [2yr] Add cookie and out_group
    https://github.com/faucetsdn/faucet/blob/e125b87385f3b1537ec92ff0c71ee4c566a1250b/tests/unit/faucet/fakeoftable.py#L462


- clib/mininet_test_base_topo.py
    - [ ] [2mo] This redoes logic from get_config()
    https://github.com/faucetsdn/faucet/blob/ae3f2acdd06620ff84577aab72e9e3d6d3f56ee8/clib/mininet_test_base_topo.py#L206
    - [ ] [4mo] Fix faucet so the test inversion is no longer required
    https://github.com/faucetsdn/faucet/blob/ae3f2acdd06620ff84577aab72e9e3d6d3f56ee8/clib/mininet_test_base_topo.py#L680


- faucet/faucet_dot1x.py
    - [ ] [11mo] Come back to. Should this be down?
    https://github.com/faucetsdn/faucet/blob/d4ff92d8eadf1f5fa54ec85165a331a762efb3c4/faucet/faucet_dot1x.py#L179


- faucet/config_parser.py
    - [ ] [2yr] refactor watcher_conf as a container
    https://github.com/faucetsdn/faucet/blob/b665179a06439deda48aef2c59581ebe2b7efbdb/faucet/config_parser.py#L303


- tests/unit/faucet/test_valve.py
    - [ ] [2yr] Check mirror packets are present/correct
    https://github.com/faucetsdn/faucet/blob/9e9ec34d1af2973c92d801e12bbd53c3004432eb/tests/unit/faucet/test_valve.py#L608


- tests/tolerance/mininet_tests.py
    - [ ] [4mo] Add the following otpions: `PROTECTED_NODES`, `PROTECTED_EDGES,` `ASSUME_TRANSITIVE_PING`, `IGNORE_SUBGRAPH`
    https://github.com/faucetsdn/faucet/blob/db3e63fe719797e9dca307840820ef7884cf4678/tests/tolerance/mininet_tests.py#L32


- faucet/valve_packet.py
    - [ ] [2yr] Python library parsers are fagile
    https://github.com/faucetsdn/faucet/blob/863b5a9f1ff5a12770a64a4794dedbe98965c568/faucet/valve_packet.py#L99


- faucet/vlan.py
    - [ ] [2yr] Not well supported by any hardware, so not used
    https://github.com/faucetsdn/faucet/blob/ae3f2acdd06620ff84577aab72e9e3d6d3f56ee8/faucet/vlan.py#L43

**Comment by mab68** [comment]
- faucet/valve_route.py
    - [ ] [2yr] Avoid relearning L3 source if same L3 source tries multiple L3 destinations quickly.
    https://github.com/faucetsdn/faucet/blob/dc8f363d107d962d142169930bcaab68ec764e5a/faucet/valve_route.py#L647


- tests/integration/mininet_tests.py
    - [ ] [6mo] Userspace DP port status not reliable
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/integration/mininet_tests.py#L1654
    - [ ] [10mo] Currently set to accommodate least hardware
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/integration/mininet_tests.py#L2829
    - [ ] [10mo] Currently set to accommodate least hardware
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/integration/mininet_tests.py#L2878
    - [ ] [2yr] Tune for loop mitigation performance
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/integration/mininet_tests.py#L3962
    - [ ] [7mo] Ensure at least on error is always generated
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/integration/mininet_tests.py#L8212


- tests/unit/faucet/test_valve_stack.py
    - [ ] [2mo] This should be False to prevent unnecessary packet-ins
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/unit/faucet/test_valve_stack.py#L537


- tests/unit/faucet/test_config.py
    - [ ] [2yr] Check alcs_in work now acl_in is deprecated
    https://github.com/faucetsdn/faucet/blob/f13396aaff9eb4b3f265c60b750a590e81fb09f0/tests/unit/faucet/test_config.py#L46
